import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { Panel } from "@llm-proxy/ui-primitives";
import { GatewayPermission, type AdminStatus, type ConfigurationInspection, type ExtensionsInspection, type ManagementContext, type ModelsInspection, type ProvidersInspection } from "@llm-proxy/management-sdk";

type Surface<T> = { value?: T; error?: string; loading: boolean };
const message = (reason: unknown) => reason instanceof Error ? reason.message : "Gateway unavailable";
function SurfaceState<T>({ name, surface, children }: { name: string; surface: Surface<T>; children: (value: T) => ReactNode }) { return <section aria-label={name}><h3>{name}</h3>{surface.loading && <p>Loading {name.toLowerCase()}…</p>}{surface.error && <p role="alert">{surface.error}</p>}{surface.value && children(surface.value)}</section>; }

export default function GatewayOverview({ context }: { context: ManagementContext }) {
  const canView = context.hasPermission(GatewayPermission.ViewOperations); const [status, setStatus] = useState<Surface<AdminStatus>>({ loading: true }); const [configuration, setConfiguration] = useState<Surface<ConfigurationInspection>>({ loading: true }); const [providers, setProviders] = useState<Surface<ProvidersInspection>>({ loading: true }); const [models, setModels] = useState<Surface<ModelsInspection>>({ loading: true }); const [extensions, setExtensions] = useState<Surface<ExtensionsInspection>>({ loading: true }); const [reloading, setReloading] = useState(false); const activeRequest = useRef<AbortController>();
  const refresh = useCallback(() => { activeRequest.current?.abort(); const controller = new AbortController(); activeRequest.current = controller; const load = <T,>(request: () => Promise<T>, set: (value: Surface<T>) => void) => { set({ loading: true }); void request().then((value) => !controller.signal.aborted && set({ value, loading: false })).catch((reason) => !controller.signal.aborted && set({ loading: false, error: message(reason) })); }; load(() => context.adminApi.getStatus(controller.signal), setStatus); load(() => context.adminApi.getConfiguration(controller.signal), setConfiguration); load(() => context.adminApi.getProviders(controller.signal), setProviders); load(() => context.adminApi.getModels(controller.signal), setModels); load(() => context.adminApi.getExtensions(controller.signal), setExtensions); }, [context]);
  useEffect(() => { if (!canView) { activeRequest.current?.abort(); return; } refresh(); return () => activeRequest.current?.abort(); }, [canView, refresh]);
  const reload = async () => { if (!status.value || reloading || !context.hasPermission(GatewayPermission.Reload) || !await context.confirm(`Reload revision ${status.value.active_revision}?`)) return; setReloading(true); try { const result = await context.adminApi.reload(status.value.active_revision); context.notify(result.restart_required ? "Reload complete; restart remains required." : "Reload complete."); refresh(); } catch (reason) { context.notify(`Reload failed: ${message(reason)}`); } finally { setReloading(false); } };
  if (!canView) return <Panel><h2>Gateway management</h2><p role="alert">Gateway operations are not permitted for this session.</p></Panel>;
  return <Panel><h2>Gateway management</h2><button onClick={refresh}>Refresh operational state</button>{context.hasPermission(GatewayPermission.Reload) && <button onClick={() => void reload()} disabled={!status.value || reloading}>{reloading ? "Reloading…" : "Reload configuration"}</button>}<SurfaceState name="Gateway state" surface={status}>{(value) => <dl><dt>Gateway version</dt><dd>{value.gateway_version}</dd><dt>Active revision</dt><dd>{value.active_revision}</dd><dt>Persisted revision</dt><dd>{value.persisted_revision}</dd><dt>Restart required</dt><dd>{String(value.restart_required)}</dd><dt>Management bind</dt><dd>{value.management_bind}</dd></dl>}</SurfaceState><SurfaceState name="Interfaces and configuration" surface={configuration}>{(value) => <p>Configuration revision: {value.revision}; interfaces: {Object.keys(value.configuration.interfaces ?? {}).join(", ") || "none"}</p>}</SurfaceState><SurfaceState name="Provider instances" surface={providers}>{(value) => <ul>{value.providers.map((item) => <li key={item.name}>{item.name} ({item.extension_id}) — {item.active ? "active" : "inactive"}; capabilities: {Object.keys(item.capabilities).join(", ") || "none"}</li>)}</ul>}</SurfaceState><SurfaceState name="Models and aliases" surface={models}>{(value) => <ul>{value.models.map((item) => <li key={item.name}>{item.name} → {item.upstream_model} via {item.provider}; aliases: {Object.values(item.aliases).flat().join(", ") || "none"}</li>)}</ul>}</SurfaceState><SurfaceState name="Extensions" surface={extensions}>{(value) => <><ul>{value.extensions.map((item) => <li key={item.extension_id}>{item.display_name} {item.package_version}; capabilities: {Object.keys(item.capabilities).join(", ") || "none"}</li>)}</ul>{context.hasPermission(GatewayPermission.ViewDiagnostics) && <ul aria-label="Diagnostics">{value.diagnostics.map((item, index) => <li key={`${item.source}-${index}`}>{item.source}: {item.message}</li>)}</ul>}</>}</SurfaceState></Panel>;
}
